# Generated by Django 5.2.1 on 2025-05-25 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posicion',
            name='forma',
        ),
        migrations.RemoveField(
            model_name='posicion',
            name='proximo_rival',
        ),
    ]
