# Generated by Django 5.2.1 on 2025-05-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_posicion_forma_remove_posicion_proximo_rival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadisticasequipo',
            name='goals_per_match',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
