# Generated by Django 5.2.1 on 2025-06-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_estadisticasequipo_goals_per_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
